@port = 3002

GET http://localhost:{{port}}/api/notes/

###
GET http://localhost:{{port}}/api/notes/1

###
DELETE http://localhost:{{port}}/api/notes/3

###
POST http://localhost:{{port}}/api/notes/
Content-Type: application/json

{
    "content": "aaaaa",
    "kek": "nom"
}